CREATE TABLE [Log] (
[Id] integer PRIMARY KEY AUTOINCREMENT NOT NULL,
[Jid] VARCHAR2(1000) NOT NULL,
[From] VARCHAR2(1000) NOT NULL,
[Message] VARCHAR2(1000) NOT NULL,
[Hash] VARCHAR2(40),
[IsDelay] BOOLEAN NOT NULL DEFAULT FALSE,
[Date] TIMESTAMP NOT NULL);
CREATE INDEX [log_jid_date] ON [Log] ([Jid], [Date]);