CREATE TABLE [Log] (
[Id] integer PRIMARY KEY AUTOINCREMENT NOT NULL,
[Jid] VARCHAR2(1000) NOT NULL,
[From] VARCHAR2(1000) NOT NULL,
[Message] VARCHAR2(1000) NOT NULL,
[Date] TIMESTAMP NOT NULL);